name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/setup-checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run test (headless)
        run: |
          pytest --headless --html=reports/pytest_report.html